# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mensajes.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emensajes.proto\x12\x03p2p\x1a\x1bgoogle/protobuf/empty.proto\"\x11\n\x0fRecursosRequest\"$\n\x10RecursosResponse\x12\x10\n\x08recursos\x18\x01 \x03(\t\";\n\x0e\x41rchivoRequest\x12\x16\n\x0enombre_archivo\x18\x01 \x01(\t\x12\x11\n\tcontenido\x18\x02 \x01(\x0c\"$\n\x0f\x41rchivoResponse\x12\x11\n\tcontenido\x18\x01 \x01(\x0c\x32\xd1\x01\n\x0bServidorP2P\x12\x42\n\x11\x43onsultarRecursos\x12\x14.p2p.RecursosRequest\x1a\x15.p2p.RecursosResponse\"\x00\x12?\n\x10\x44\x65scargarArchivo\x12\x13.p2p.ArchivoRequest\x1a\x14.p2p.ArchivoResponse\"\x00\x12=\n\x0cSubirArchivo\x12\x13.p2p.ArchivoRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mensajes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RECURSOSREQUEST']._serialized_start=52
  _globals['_RECURSOSREQUEST']._serialized_end=69
  _globals['_RECURSOSRESPONSE']._serialized_start=71
  _globals['_RECURSOSRESPONSE']._serialized_end=107
  _globals['_ARCHIVOREQUEST']._serialized_start=109
  _globals['_ARCHIVOREQUEST']._serialized_end=168
  _globals['_ARCHIVORESPONSE']._serialized_start=170
  _globals['_ARCHIVORESPONSE']._serialized_end=206
  _globals['_SERVIDORP2P']._serialized_start=209
  _globals['_SERVIDORP2P']._serialized_end=418
# @@protoc_insertion_point(module_scope)
